name: doghero_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  rename_app: ^1.6.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  flutter_custom_clippers: ^2.1.0
  provider: ^6.1.2
  get_it: ^8.0.0
  injectable: ^2.5.0
  curved_navigation_bar: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.4.0
  injectable_generator: ^2.1.5
  # add build runner if not already added  
  build_runner: ^2.3.3
  

flutter:
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Bold.ttf
  assets:
    - assets/dogs.json
    - assets/Logo.png
    - assets/dogopng.png
    - assets/images/pantalla_splash.jpeg
    - assets/images/home_screen.png
    - assets/images/logo_nuevo.jpeg


