name: doghero_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  rename_app: ^1.6.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  flutter_custom_clippers: ^2.1.0
  provider: ^6.1.2
  get_it: ^8.0.0
  injectable: ^2.5.0
  curved_navigation_bar: ^1.0.6
  mailer: ^6.2.0
  firebase_messaging: ^15.1.3
  google_maps_flutter: ^2.10.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  camera: ^0.11.0+2
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  path: ^1.9.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0
  injectable_generator: ^2.1.5
  # add build runner if not already added  
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_nuevo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21  

flutter:
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Bold.ttf
  assets:
    - assets/dogs.json
    - assets/Logo.png
    - assets/dogopng.png
    - assets/images/pantalla_splash.jpeg
    - assets/images/home_screen.png
    - assets/images/logo_nuevo.png

